-- 한 쿼리로 하나의 게시글 정보 + 여러 개의 첨부파일 정보 -> BOARDDTO
SELECT BOARD_NO
     , BOARD_TITLE
     , USER_ID
     , BOARD_CONTENT
     , TO_CHAR(REGIST_DATE, 'YYYY-MM-DD') AS REGIST_DATE
     , FILE_PATH
     , FILESYSTEM_NAME
     , ORIGINAL_NAME
FROM BOARD B
JOIN MEMBER M ON (BOARD_WRITER = USER_NO)
LEFT JOIN ATTACHMENT ON (REF_TYPE = 'B' AND BOARD_NO = REF_NO) /* 첨부파일이 없는 게시글도 조회 */
WHERE B.STATUS = 'Y'
    AND BOARD_NO = 17;